name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  sonarcloud_analysis:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Java (Temurin JDK 11)
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'  # Temurin is a JDK distribution

    # Step 3: Install Sonar Scanner
    - name: Install Sonar Scanner
      run: |
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
        unzip sonar-scanner-cli-4.8.0.2856-linux.zip
        sudo mv sonar-scanner-4.8.0.2856-linux /usr/local/sonar-scanner
        echo "export PATH=\$PATH:/usr/local/sonar-scanner/bin" >> $GITHUB_ENV
        echo "Sonar Scanner installed."

    # Step 4: SonarCloud analysis
    - name: Run SonarCloud analysis
      run: |
        sonar-scanner \
          -Dsonar.projectKey=bbfeea321fdaf9a89b0556b70c1eddcd95a54caa \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -X  # Enable full debug output
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

